[package]
name = "duckdb_chess"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[dependencies]
duckdb = { version = "1.4.3", features = ["vtab-loadable", "vscalar"] }
duckdb-ext-macros = "0.1.0"
libduckdb-sys = { version = "1.4.3", features = ["loadable-extension"] }
pgn-reader = "0.28"
shakmaty = "0.29"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
glob = "0.3"
